### ISSUE TITLE
pykafka balancedconsumer: PartitionOwnedError\ ConsumerStoppedException 

### ISSUE THREAD

**Issue by migowei0621** [migowei0621/pykafka-usage#1]
在使用pykafka的balancedconsumer时当对同一个topic启动多个consumer时会报 ConsumerStoppedExceptoin Error：

Traceback (most recent call last):
  File "/home/loshu/.local/lib/python3.5/site-packages/pykafka/balancedconsumer.py", line 748, in consume
    message = self._consumer.consume(block=block, unblock_event=self._rebalancing_in_progress)
AttributeError: 'NoneType' object has no attribute 'consume'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/consumer.py", line 131, in <module>
    client.balanced_consumer()
  File "src/consumer.py", line 39, in balanced_consumer
    msg = consumer.consume()
  File "/home/loshu/.local/lib/python3.5/site-packages/pykafka/balancedconsumer.py", line 757, in consume
    raise ConsumerStoppedException
pykafka.exceptions.ConsumerStoppedException

原因及解决方案 https://blog.csdn.net/liuxingen/article/details/53335904

**Comment by migowei0621** [comment]
consumer_timeout_ms=-1的问题：http://www.itdaan.com/blog/2017/07/16/2470e62b642bf7b60b2bccf24e43b9d0.html
